<<<<<<< Updated upstream
# hyprpaper — wallpaper path injected by scripts/switch-theme.sh
# THEME:START
wallpaper {
    monitor =
    path = /home/liam/Github/dotfiles/wallpapers/everforest.png
    fit_mode = cover
}
# THEME:END

=======
preload = /home/d1srupt3d/Documents/dotfiles/wallpapers/everforest.png
wallpaper = eDP-1,/home/d1srupt3d/Documents/dotfiles/wallpapers/everforest.png
wallpaper = 1,/home/d1srupt3d/Documents/dotfiles/wallpapers/everforest.png
>>>>>>> Stashed changes
splash = false
