# Execute your favorite apps at launch
exec-once = waybar
exec-once = sleep 2 && hyprpaper
exec-once = sleep 3 && hyprctl hyprpaper wallpaper "eDP-1,/home/d1srupt3d/Documents/dotfiles/wallpapers/clock.jpg"
exec-once = swaync
exec-once = blueman-applet
exec-once = nm-applet
