# Hyprland General Configuration - Graphite Theme
# See https://wiki.hyprland.org/Configuring/Variables/ for more
general {
    gaps_in = 8
    gaps_out = 16
    border_size = 3
    col.active_border = $color_border1 $color_border2 $color_border3 45deg
    col.inactive_border = $color_border_inactive
    layout = dwindle
    resize_on_border = true
}
