# See https://wiki.hyprland.org/Configuring/Variables/ for more
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    
    # Wake screen features
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    
    # VRR (Variable Refresh Rate) for gaming
    vrr = 1
    
    # Window swallowing (terminal opens, hides when opening GUI)
    enable_swallow = true
    swallow_regex = ^(ghostty)$
}